### ISSUE TITLE
GIL PEP684 теперь вполне себе работает с CPU-bound 

### ISSUE THREAD

**Issue by kohiry** [yakimka/python_interview_questions#16]
PEP 684 вводит GIL для каждого интерпретатора, так что теперь можно создавать подинтерпретаторы с уникальным GIL для каждого интерпретатора. Это позволяет программам на Python использовать все преимущества нескольких ядер процессора. В настоящее время эта возможность доступна только через C-API, хотя API для Python ожидается в версии 3.13.

https://peps.python.org/pep-0684/

**Comment by yakimka** [comment]
3.13 ещё не релизнулся, а то что существует в 3.12 еще не имеет публичного API
